Ordering_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('main/',include('main.urls')),




]

backend/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static


app_name = 'backend'

urlpatterns =[


        path('', views.home2, name='home2'),
        path('accounts', views.accounts, name='accounts'),
        path('show', views.show, name='show'),
        path('ship', views.ship, name='ship' ),
        path('reports', views.reports, name='ship') ,

    #login
        path('login', views.loginview, name='login'),
        path('login/Loginprocess', views.Loginprocess, name='Loginprocess'),
        path('logout', views.processlogout, name='logout'),

        path('add' , views.add, name='add'),
        path('Processadd', views.Processadd, name='Processadd'),
        path('isearch' , views.isearch, name='isearch'),

        path('products', views.productshow, name='products'),
        path('Productprocess', views.Productprocess, name='Productprocess'),
        path('Meatprocess', views.Meatprocess, name='Meatprocess'),


          # user updates show delete
        path('<int:user_id>/detail/', views.detail, name='detail'),
        path('<int:user_id>/deletes/', views.deletes, name='deletes'),
        path('<int:user_id>/edits/', views.edits, name='edits'),
        path('<int:user_id>/processedit/', views.proccessedit, name='processedit'),

        # meat update delete
         path('<int:meat_id>/mdetail/', views.mdetail, name='mdetail'),
         path('<int:meat_id>/mdelete/', views.mdelete, name='mdelete'),
         path('<int:meat_id>/medit/', views.medit, name='medit'),
         path('<int:meat_id>/mproccessedit/', views.mproccessedit, name='mproccessedit'),
         path('search', views.search, name='search'),

        # pancit update delete
         path('<int:pancit_id>/pdetails/', views.pdetails, name='pdetails'),
         path('<int:pancit_id>/pdelete/', views.pdelete, name='pdelete'),
         path('<int:pancit_id>/pedit/', views.pedit, name='pedit'),
         path('<int:pancit_id>/pproccessedit/', views.pproccessedit, name='pproccessedit'),
         path('psearch', views.psearch, name='psearch'),



        path('proccessing',views.procesingorders,name='proccessing'),
        path('food_orders',views.food_orders,name='food_orders'),
        path('meatpage', views.meatpage, name='meatpage') ,
        path('pancitpage', views.pancitpage, name='pancitpage') ,
        path('home', views.home, name='home'),


    #------------------------------ front end --------

         path('home2', views.home3, name='home2')



   ]  +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
                  path('store', views.store, name="store"),
                  path('cart/', views.cart, name="cart"),
                  path('checkout/', views.checkout, name="checkout"),

                  path('update_item/', views.updateItem, name="update_item"),
                  path('process_order/', views.processOrder, name="process_order"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

backend/models.py
from django.db import models
from datetime import datetime
from django .utils import timezone
import os, random
from django.utils.html import mark_safe

# Create your models here.

now = timezone.now()


def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghjklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.format(imageid=instance,
                                                                                        basename=basefilename,
                                                                                        randomstring=randomstr,
                                                                                        ext=file_extension,
                                                                                        year=_now.strftime('%Y'),
                                                                                        month=_now.strftime('%m'),
                                                                                        day=_now.strftime('%d'))

#----- users
class user(models.Model):
    user_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')
    user_uid = models.IntegerField( max_length=500, verbose_name='UID')
    user_fname = models.CharField(max_length=200, verbose_name='First name')
    user_lname = models.CharField(max_length=200, verbose_name="Last name")
    user_position = models.CharField(max_length=200, verbose_name='Position')
    user_username = models.CharField(unique=True,max_length=200, verbose_name="Username")
    user_password = models.CharField(max_length=200, verbose_name="Password")
    pub_date = models.DateField(default=now)

    def __str__(self):
        return self.user_username

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.user_image))



#----- Comments
class Comment(models.Model):
    user_com =models.ForeignKey(user, on_delete=models.CASCADE, related_name='comments')
    name     = models.CharField(max_length=100)
    email    = models.EmailField(default='null')
    body     = models.TextField(default='null')
    created_on  = models.DateTimeField('date commented')
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'comment {} by {} '.format(self.body, self.name)

#--- porduct
class Product(models.Model):
    pro_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg',null=True, blank= True)
    pro_id = models.CharField(max_length=50, verbose_name="Product id")
    pro_name =models.CharField(max_length=200, null=False, verbose_name="Product name")
    pro_price = models.DecimalField(max_digits=10, decimal_places=2)
    pro_size = models.CharField(max_length=200, verbose_name="Size")
    Catergoty = models.CharField(max_length=200, verbose_name="Catergory")
    digital =models.BooleanField(default=False, null=True, blank=False)


    def __str__(self):
        return self.pro_name

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.pro_image))
    
   


 #meatproduct

class Meat(models.Model):
    m_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')
    m_id = models.CharField(max_length=50, unique=True, verbose_name="Product id")
    m_name =models.CharField(max_length=200, null=False, verbose_name="Product name")
    m_price = models.DecimalField(max_digits=10, decimal_places=2)
    m_size = models.CharField(max_length=200, verbose_name="Size")
    m_cat = models.CharField(max_length=200, verbose_name="Catergory")

    def __str__(self):
        return self.m_id

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.m_image))


# product meat

backend/views.py
from django.shortcuts import render, get_object_or_404 , reverse
from django.http import HttpResponseRedirect, Http404
from . models import user , Product  ,Meat
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from main.models import order, orderitem, Shippingaddress
from  django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
#---- view


def home2(request):
    return render(request,'admins_/Home.html')
def home3(request):
    return render(request, 'frontend/home2.html')


def isearch(request):
     term = request.GET.get('search','')
     user_list =user.objects.filter(Q (user_fname__icontains=term) | Q(user_lname__icontains=term)).order_by('-id')

     return render(request, 'admins_/index.html', {'user_list': user_list})

 #--- meat search

def search(request):
    term = request.GET.get('search','')
    m_list = Meat.objects.filter(Q(m_name__icontains=term)).order_by('-id')

    return render(request, 'admins_/products.html', {'m_list': m_list}  )

# pancit search

def psearch(request):
    term = request.GET.get('psearch','')
    pro_list = Product.objects.filter(Q(pro_name__icontains=term)).order_by('-id')

    return render(request, 'admins_/products.html', {'pro_list': pro_list}  )


def accounts(request):
    user_list = user.objects.order_by('pub_date')
    context = {'user_list': user_list}

    return render(request, 'admins_/index.html', context)


def ship(request):
    ships = Shippingaddress.objects.all()
    shipcounts =   ships.count()
    context = {'ships': ships, 'shipcounts':shipcounts}

    return render(request, 'admins_/Foodorders.html', context)




def show(request):
    user_list = user.objects.order_by('pub_date')
    context = {'user_list': user_list}

    return render(request, 'admins_/index.html', context)


# adding new user

def Processadd(request):

    
    uid = request.POST.get('uid')
    
    position = request.POST.get('position')
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    uname = request.POST.get('uname')
    pword = request.POST.get('pword')
    start = request.POST.get('start')


    if request.FILES.get('image'):
        user_pic = request.FILES.get('image')
    else:
        user_pic = 'profile/image.jpg'
    try:                                                                                                        
        n = user.objects.get(user_username=uname)

        return render(request, 'admins_/account.html', { 'error_message': "This Username " + uname +  "already exist"})

    except ObjectDoesNotExist:
        users = user.objects.create(user_uid=uid, user_username=uname, user_position=position, user_fname=fname, user_lname=lname
                                    ,pub_date=start, user_password=pword,user_image=user_pic)
        users.save()

        return HttpResponseRedirect('/backend/accounts')



#delete details
def deletes(request, user_id):
    user.objects.filter(id=user_id).delete()
    return HttpResponseRedirect('/backend/accounts')

#edits

def edits(request, user_id):
    try:
        users = user.objects.get(pk=user_id)

    except user.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/edit.html', {'users': users})

def proccessedit(request, user_id):
    users = get_object_or_404(user, pk=user_id)
    profile_pic = request.FILES.get('image')
    try:

        position = request.POST.get('position')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        uname = request.POST.get('uname')
        pword = request.POST.get('pword')

    except (KeyError, user.DoesNotExist):
        return render(request,'admins_/detail.html', {
            'users':users,
            'error_message': "There is a problem on updating the record"
        })
    else:
        user_profile =user.objects.get(id=user_id)
        user_profile.user_position = position
        user_profile.user_fname = fname
        user_profile.user_lname = lname
        user_profile.user_uname = uname
        user_profile.user_password = pword
        if profile_pic:
            user_profile.user_image = profile_pic
        user_profile.save()
        return HttpResponseRedirect(reverse('backend:detail', args=(user_id, )))


def detail(request, user_id):
    try:
        users = user.objects.get(pk=user_id)

    except user.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/detail.html', {'users': users})


#----- add products

def productshow(request):
        pro_list = Product.objects.order_by('pro_id')
        m_list = Meat.objects.order_by('m_id')

        context = {'pro_list': pro_list, 'm_list': m_list}

        return render(request, 'admins_/products.html', context)



# THIS IS FOR THE MEAT PRODUCT ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


def Meatprocess(request):
    mid = request.POST.get('pid')
    mname = request.POST.get('proname')
    mprice = request.POST.get('price')
    mcategory = request.POST.get('cat')
    msize = request.POST.get('size')

    if request.FILES.get('image'):
        mpro_pic = request.FILES.get('image')
    else:
        mpro_pic = 'profile/image.jpg'
    try:
        n = Meat.objects.get(m_id=mid)

        return render(request, 'forms/addpancit.html', {'error_message': "This product " + mid +""+ mname + "already exist"})

    except ObjectDoesNotExist:
        users = Meat.objects.create(m_id=mid, m_name=mname, m_price=mprice, m_cat=mcategory, m_size=msize
                                       , m_image=mpro_pic)
        users.save()

        return HttpResponseRedirect(reverse('backend:products'))


# meat edits --------------------------------------------------------------------------->>>>>

def mdetail(request, meat_id):
    try:
        meats = Meat.objects.get(pk=meat_id)

    except Meat.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/mdetail.html', {'meats': meats})


# delete details
def mdelete(request, meat_id):
    Meat.objects.filter(id=meat_id).delete()
    return HttpResponseRedirect(reverse('backend:products'))


# edits

def medit(request, meat_id):
    try:
        meats = Meat.objects.get(pk=meat_id)

    except Meat.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'forms/meatedit.html', {'meats': meats})


def mproccessedit(request, meat_id):
    meats = get_object_or_404(Meat, pk=meat_id)
    profile_pic = request.FILES.get('image')
    try:
        mid = request.POST.get('pid')
        mname = request.POST.get('proname')
        mprice = request.POST.get('price')
        mcategory = request.POST.get('cat')
        msize = request.POST.get('size')

    except (KeyError, user.DoesNotExist):
        return render(request, 'admins_/mdetail.html', {
            'meats': meats,
            'error_message': "There is a problem on updating the record"
        })
    else:
        meat_profile = Meat.objects.get(id=meat_id)
        meat_profile.m_id = mid
        meat_profile.m_name = mname
        meat_profile.m_price = mprice
        meat_profile.m_cat = mcategory
        meat_profile.m_size = msize
        if profile_pic:
            meat_profile.m_image = profile_pic
        meat_profile.save()
        return HttpResponseRedirect(reverse('backend:mdetail', args=(meat_id, )))


#------------------------------------------------ product pancit--------------
    
def Productprocess(request):
    id= request.POST.get('pid')
    name = request.POST.get('proname')
    price = request.POST.get('price')
    category = request.POST.get('cat')
    size = request.POST.get('size')


    if request.FILES.get('image'):
        pro_pic = request.FILES.get('image')
    else:
        pro_pic = 'profile/image.jpg'
    try:
        n =Product.objects.get(pro_id=id)

        return render(request, 'forms/addpancit.html',{ 'error_message': "This product " + id +  "already exist"})

    except ObjectDoesNotExist:
        users = Product.objects.create(pro_id=id, pro_name=name, pro_price=price,  Catergoty=category, pro_size=size
                                    ,pro_image=pro_pic)
        users.save()

        return HttpResponseRedirect(reverse('backend:products'))



#------------------- Pancit Editing ---------



def pdetails(request, pancit_id):
    try:
        pancit = Product.objects.get(pk=pancit_id)

    except Product.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/pdetail.html', {'pancit': pancit})


# delete details
def pdelete(request,pancit_id):
    Product.objects.filter(id=pancit_id).delete()
    return HttpResponseRedirect(reverse('backend:products'))


# edits

def pedit(request, pancit_id):
    try:
        pancit = Product.objects.get(pk=pancit_id)

    except Productprocess.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'forms/pancitedit.html', {'pancit': pancit})


def pproccessedit(request, pancit_id):
    pancit = get_object_or_404(Product, pk=pancit_id)
    profile_pic = request.FILES.get('image')
    try:
        id = request.POST.get('pid')
        name = request.POST.get('proname')
        price = request.POST.get('price')
        category = request.POST.get('cat')
        size = request.POST.get('size')

    except (KeyError, Productprocess.DoesNotExist):
        return render(request, 'admins_/pdetail.html', {
            'pancit': pancit,
            'error_message': "There is a problem on updating the record"
        })
    else:
        pancit_profile = Product.objects.get(id=pancit_id)
        pancit_profile.m_id = id
        pancit_profile.m_name = name
        pancit_profile.m_price = price
        pancit_profile.Catergoty = category

backend/templates/forms/addmeat.html
{% extends 'base.html' %}

{% block title %}

    Pancit
{% endblock %}

{% block content %}

 <style>

 .containers{
 margin-left: 25%;
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.containers .title{
  font-size: 25px;
  font-weight: 500;

}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: blue;
}

</style>

{% if error_message %}

<p class="alert alert-danger">
    <strong> {{ error_message }}</strong>
</p>

{% endif  %}

                <h1 class="text-cencter mb-4"> ADD NEW PRODUCT FOR MEAT</h1>

                <div class="containers">
                    <form action="{% url 'backend:Meatprocess' %}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}

                        <div class="form-group">
                             <label> Product id</label>
                            <input type="text" name="pid" id="pid" class="form-control" required>
                             </div>

                        <div class="form-group">
                            <label> Product Name</label>
                            <input type="text" name="proname" id="proname" class="form-control" required>
                             </div>

                        <div class="form-group">
                            <label> Price </label>
                            <input type="number" name="price" id="price" class="form-control"required>
                                    </div>

                        <div class="form-group">
                            <label> Size </label>
                            <input type="text" name="size " id="size " class="form-control"required>
                             </div>

                        <div class="form-group">
                             <label>Cateregory </label>
                            <input type="text" name="cat" id="cat" class="form-control"required>
                             </div>


                        <div class="form-group">
                        <label >Upload image Product </label>
                        <input type="file" id="image" name="image" class="form-control"required>

                            <button type="submit" class="btn btn-success mt-2 ">Add this product</button>

                         </div>


                    </form>

                </div>

{% endblock %}

backend/templates/forms/addpancit.html
{% extends 'base.html' %}

{% block title %}

    Pancit
{% endblock %}

{% block content %}
          <style>

 .containers{
 margin-left: 25%;
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
 
}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: blue;
}

      </style>



        {% if error_message %}

        <p class="alert alert-danger">
         <strong> {{ error_message }}</strong>
        </p>

        {% endif  %}


    <h1 class="text-cencter mb-4"> ADD For PANCIT PRODUCT</h1>

            <div class="containers">
                <form action="{% url 'backend:Productprocess' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                         <label> Product id</label>
                        <input type="text" name="pid" id="pid" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label> Product Name</label>
                        <input type="text" name="proname" id="proname" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label> Price </label>
                        <input type="number" name="price" id="price" class="form-control"required>
                                </div>

                    <div class="form-group">
                        <label> Size </label>
                        <input type="text" name="size " id="size " class="form-control"required>
                     </div>

                    <div class="form-group">
                         <label>Cateregory </label>
                        <input type="text" name="cat" id="cat" class="form-control"required>
                    </div>


                    <div class="form-group">
                    <label >Upload image Product </label>
                    <input type="file" id="image" name="image" class="form-control"required>

                        <button type="submit" class="btn btn-success mt-2 ">Add this product</button>

                     </div>

                </form>

               </div>

{% endblock %}

backend/templates/forms/login.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



{% block content %}


            <div class="container">
                <img src="{% static 'images/favicon.jpg' %} ">
                <div class="row mt-5">
                    <div class="col-md-6 m-auto">
                       {% if error_message %}
                         <p class="alert alert-danger">
                             <strong> {{ error_message }} </strong>
                         </p>
                        {% endif %}

                        <div class="text-center">
                            <h2> Login Form </h2>
                            </div>

                        <form action="{% url 'backend:Loginprocess' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label> Username </label>
                                <input  type="text" name="username" id="username" class="form-control" placeholder="enter username"
                                autocomplete="off">

                                <label> Password </label>
                                <input  type="password" name="password" id="password" class="form-control" placeholder="enter password"
                                >

                                <button type="submit" class="btn btn-success"> login </button  >

                            </div>


                        </form>

                    </div>
                <!-- end row-->
                </div>
                <!--container end-->
            </div>



{% endblock %}

backend/templates/forms/meatedit.html
{% extends 'base.html' %}

{% block title %}

    Create Account

{% endblock %}

{% block content %}

<style>

.containers{

  margin-left: 25%;
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}




</style>

                  {% if error_message %}
                    <p class="alert alert-danger">
                    <strong> {{ error_message }}</strong>
                    </p>
                    {% endif  %}


  <div class="containers">


              <h2> Create new Admin/Staff Account </h2>


                <form action="{% url 'backend:mproccessedit' meats.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                     {% csrf_token %}

                        <div class="form-group">
                             <label> Product id</label>
                            <input type="text" name="pid" id="pid" class="form-control" required value="{{ meats.m_id }}">
                             </div>

                        <div class="form-group">
                            <label> Product Name</label>
                            <input type="text" name="proname" id="proname" class="form-control" required value="{{ meats.m_name }}">
                             </div>

                        <div class="form-group">
                            <label> Price </label>
                            <input type="number" name="price" id="price" class="form-control"required value="{{ meats.m_price }}">
                                    </div>

                        <div class="form-group">
                            <label> Size </label>
                            <input type="text" name="size " id="size " class="form-control"required value="{{ meats.m_size }}">
                             </div>

                        <div class="form-group">
                             <label>Cateregory </label>
                            <input type="text" name="cat" id="cat" class="form-control"required value="{{ meats.m_cat }}">
                             </div>


                        <div class="form-group">
                        <label >Upload image Product </label>
                        <input type="file" id="image" name="image" class="form-control">

                            <button type="submit" class="btn btn-success mt-2 ">Proccess</button>

                         </div>


                    </form>

                </div>

{% endblock %}

backend/templates/forms/pancitedit.html
{% extends 'base.html' %}

{% block title %}

    Create Account

{% endblock %}

{% block content %}

<style>

.containers{

  margin-left: 25%;
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}




</style>

                  {% if error_message %}
                    <p class="alert alert-danger">
                    <strong> {{ error_message }}</strong>
                    </p>
                    {% endif  %}


  <div class="containers">


              <h2> UPDATE PRODUCT INFORMATION </h2>


                <form action="{% url 'backend:pproccessedit' pancit.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                     {% csrf_token %}

                        <div class="form-group">
                             <label> Product id</label>
                            <input type="text" name="pid" id="pid" class="form-control" required value="{{ pancit.pro_id }}">
                             </div>

                        <div class="form-group">
                            <label> Product Name</label>
                            <input type="text" name="proname" id="proname" class="form-control" required value="{{ pancit.pro_name }}">
                             </div>

                        <div class="form-group">
                            <label> Price </label>
                            <input type="number" name="price" id="price" class="form-control"required value="{{ pancit.pro_price }}">
                                    </div>

                        <div class="form-group">
                            <label> Size </label>
                            <input type="text" name="size " id="size " class="form-control"required value="{{ pancit.pro_size }}">
                             </div>

                        <div class="form-group">
                             <label>Cateregory </label>
                            <input type="text" name="cat" id="cat" class="form-control"required value="{{ pancit.Catergoty }}">
                             </div>


                        <div class="form-group">
                        <label >Upload image Product </label>
                        <input type="file" id="image" name="image" class="form-control">

                            <button type="submit" class="btn btn-success mt-2 ">Proccess</button>

                         </div>


                    </form>

                </div>

{% endblock %}