Ordering_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('main/',include('main.urls')),




]

backend/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static


app_name = 'backend'

urlpatterns =[


        path('', views.home2, name='home2'),
        path('accounts', views.accounts, name='accounts'),
        path('show', views.show, name='show'),
        path('ship', views.ship, name='ship' ),
        path('reports', views.reports, name='ship') ,

    #login
        path('login', views.loginview, name='login'),
        path('login/Loginprocess', views.Loginprocess, name='Loginprocess'),
        path('logout', views.processlogout, name='logout'),

        path('add' , views.add, name='add'),
        path('Processadd', views.Processadd, name='Processadd'),
        path('isearch' , views.isearch, name='isearch'),

        path('products', views.productshow, name='products'),
        path('Productprocess', views.Productprocess, name='Productprocess'),
        path('Meatprocess', views.Meatprocess, name='Meatprocess'),


          # user updates show delete
        path('<int:user_id>/detail/', views.detail, name='detail'),
        path('<int:user_id>/deletes/', views.deletes, name='deletes'),
        path('<int:user_id>/edits/', views.edits, name='edits'),
        path('<int:user_id>/processedit/', views.proccessedit, name='processedit'),

        # meat update delete
         path('<int:meat_id>/mdetail/', views.mdetail, name='mdetail'),
         path('<int:meat_id>/mdelete/', views.mdelete, name='mdelete'),
         path('<int:meat_id>/medit/', views.medit, name='medit'),
         path('<int:meat_id>/mproccessedit/', views.mproccessedit, name='mproccessedit'),
         path('search', views.search, name='search'),

        # pancit update delete
         path('<int:pancit_id>/pdetails/', views.pdetails, name='pdetails'),
         path('<int:pancit_id>/pdelete/', views.pdelete, name='pdelete'),
         path('<int:pancit_id>/pedit/', views.pedit, name='pedit'),
         path('<int:pancit_id>/pproccessedit/', views.pproccessedit, name='pproccessedit'),
         path('psearch', views.psearch, name='psearch'),



        path('proccessing',views.procesingorders,name='proccessing'),
        path('food_orders',views.food_orders,name='food_orders'),
        path('meatpage', views.meatpage, name='meatpage') ,
        path('pancitpage', views.pancitpage, name='pancitpage') ,
        path('home', views.home, name='home'),


    #------------------------------ front end --------

         path('home2', views.home3, name='home2')



   ]  +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
                  path('store', views.store, name="store"),
                  path('cart/', views.cart, name="cart"),
                  path('checkout/', views.checkout, name="checkout"),

                  path('update_item/', views.updateItem, name="update_item"),
                  path('process_order/', views.processOrder, name="process_order"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

backend/models.py
from django.db import models
from datetime import datetime
from django .utils import timezone
import os, random
from django.utils.html import mark_safe

# Create your models here.

now = timezone.now()


def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghjklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.format(imageid=instance,
                                                                                        basename=basefilename,
                                                                                        randomstring=randomstr,
                                                                                        ext=file_extension,
                                                                                        year=_now.strftime('%Y'),
                                                                                        month=_now.strftime('%m'),
                                                                                        day=_now.strftime('%d'))

#----- users
class user(models.Model):
    user_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')
    user_uid = models.IntegerField( max_length=500, verbose_name='UID')
    user_fname = models.CharField(max_length=200, verbose_name='First name')
    user_lname = models.CharField(max_length=200, verbose_name="Last name")
    user_position = models.CharField(max_length=200, verbose_name='Position')
    user_username = models.CharField(unique=True,max_length=200, verbose_name="Username")
    user_password = models.CharField(max_length=200, verbose_name="Password")
    pub_date = models.DateField(default=now)

    def __str__(self):
        return self.user_username

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.user_image))



#----- Comments
class Comment(models.Model):
    user_com =models.ForeignKey(user, on_delete=models.CASCADE, related_name='comments')
    name     = models.CharField(max_length=100)
    email    = models.EmailField(default='null')
    body     = models.TextField(default='null')
    created_on  = models.DateTimeField('date commented')
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'comment {} by {} '.format(self.body, self.name)

#--- porduct
class Product(models.Model):
    pro_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg',null=True, blank= True)
    pro_id = models.CharField(max_length=50, verbose_name="Product id")
    pro_name =models.CharField(max_length=200, null=False, verbose_name="Product name")
    pro_price = models.DecimalField(max_digits=10, decimal_places=2)
    pro_size = models.CharField(max_length=200, verbose_name="Size")
    Catergoty = models.CharField(max_length=200, verbose_name="Catergory")
    digital =models.BooleanField(default=False, null=True, blank=False)


    def __str__(self):
        return self.pro_name

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.pro_image))
    
   


 #meatproduct

class Meat(models.Model):
    m_image = models.ImageField(upload_to=image_path, default='profile_pic/image.jpg')
    m_id = models.CharField(max_length=50, unique=True, verbose_name="Product id")
    m_name =models.CharField(max_length=200, null=False, verbose_name="Product name")
    m_price = models.DecimalField(max_digits=10, decimal_places=2)
    m_size = models.CharField(max_length=200, verbose_name="Size")
    m_cat = models.CharField(max_length=200, verbose_name="Catergory")

    def __str__(self):
        return self.m_id

    def image_tag(self):
        return mark_safe('<img src ="/backend/media/%s" width ="50" height="50"/>' % (self.m_image))


# product meat

backend/views.py
from django.shortcuts import render, get_object_or_404 , reverse
from django.http import HttpResponseRedirect, Http404
from . models import user , Product  ,Meat
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from main.models import order, orderitem, Shippingaddress
from  django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
#---- view


def home2(request):
    return render(request,'admins_/Home.html')
def home3(request):
    return render(request, 'frontend/home2.html')


def isearch(request):
     term = request.GET.get('search','')
     user_list =user.objects.filter(Q (user_fname__icontains=term) | Q(user_lname__icontains=term)).order_by('-id')

     return render(request, 'admins_/index.html', {'user_list': user_list})

 #--- meat search

def search(request):
    term = request.GET.get('search','')
    m_list = Meat.objects.filter(Q(m_name__icontains=term)).order_by('-id')

    return render(request, 'admins_/products.html', {'m_list': m_list}  )

# pancit search

def psearch(request):
    term = request.GET.get('psearch','')
    pro_list = Product.objects.filter(Q(pro_name__icontains=term)).order_by('-id')

    return render(request, 'admins_/products.html', {'pro_list': pro_list}  )


def accounts(request):
    user_list = user.objects.order_by('pub_date')
    context = {'user_list': user_list}

    return render(request, 'admins_/index.html', context)


def ship(request):
    ships = Shippingaddress.objects.all()
    shipcounts =   ships.count()
    context = {'ships': ships, 'shipcounts':shipcounts}

    return render(request, 'admins_/Foodorders.html', context)




def show(request):
    user_list = user.objects.order_by('pub_date')
    context = {'user_list': user_list}

    return render(request, 'admins_/index.html', context)


# adding new user

def Processadd(request):

    
    uid = request.POST.get('uid')
    
    position = request.POST.get('position')
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    uname = request.POST.get('uname')
    pword = request.POST.get('pword')
    start = request.POST.get('start')


    if request.FILES.get('image'):
        user_pic = request.FILES.get('image')
    else:
        user_pic = 'profile/image.jpg'
    try:                                                                                                        
        n = user.objects.get(user_username=uname)

        return render(request, 'admins_/account.html', { 'error_message': "This Username " + uname +  "already exist"})

    except ObjectDoesNotExist:
        users = user.objects.create(user_uid=uid, user_username=uname, user_position=position, user_fname=fname, user_lname=lname
                                    ,pub_date=start, user_password=pword,user_image=user_pic)
        users.save()

        return HttpResponseRedirect('/backend/accounts')



#delete details
def deletes(request, user_id):
    user.objects.filter(id=user_id).delete()
    return HttpResponseRedirect('/backend/accounts')

#edits

def edits(request, user_id):
    try:
        users = user.objects.get(pk=user_id)

    except user.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/edit.html', {'users': users})

def proccessedit(request, user_id):
    users = get_object_or_404(user, pk=user_id)
    profile_pic = request.FILES.get('image')
    try:

        position = request.POST.get('position')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        uname = request.POST.get('uname')
        pword = request.POST.get('pword')

    except (KeyError, user.DoesNotExist):
        return render(request,'admins_/detail.html', {
            'users':users,
            'error_message': "There is a problem on updating the record"
        })
    else:
        user_profile =user.objects.get(id=user_id)
        user_profile.user_position = position
        user_profile.user_fname = fname
        user_profile.user_lname = lname
        user_profile.user_uname = uname
        user_profile.user_password = pword
        if profile_pic:
            user_profile.user_image = profile_pic
        user_profile.save()
        return HttpResponseRedirect(reverse('backend:detail', args=(user_id, )))


def detail(request, user_id):
    try:
        users = user.objects.get(pk=user_id)

    except user.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/detail.html', {'users': users})


#----- add products

def productshow(request):
        pro_list = Product.objects.order_by('pro_id')
        m_list = Meat.objects.order_by('m_id')

        context = {'pro_list': pro_list, 'm_list': m_list}

        return render(request, 'admins_/products.html', context)



# THIS IS FOR THE MEAT PRODUCT ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


def Meatprocess(request):
    mid = request.POST.get('pid')
    mname = request.POST.get('proname')
    mprice = request.POST.get('price')
    mcategory = request.POST.get('cat')
    msize = request.POST.get('size')

    if request.FILES.get('image'):
        mpro_pic = request.FILES.get('image')
    else:
        mpro_pic = 'profile/image.jpg'
    try:
        n = Meat.objects.get(m_id=mid)

        return render(request, 'forms/addpancit.html', {'error_message': "This product " + mid +""+ mname + "already exist"})

    except ObjectDoesNotExist:
        users = Meat.objects.create(m_id=mid, m_name=mname, m_price=mprice, m_cat=mcategory, m_size=msize
                                       , m_image=mpro_pic)
        users.save()

        return HttpResponseRedirect(reverse('backend:products'))


# meat edits --------------------------------------------------------------------------->>>>>

def mdetail(request, meat_id):
    try:
        meats = Meat.objects.get(pk=meat_id)

    except Meat.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/mdetail.html', {'meats': meats})


# delete details
def mdelete(request, meat_id):
    Meat.objects.filter(id=meat_id).delete()
    return HttpResponseRedirect(reverse('backend:products'))


# edits

def medit(request, meat_id):
    try:
        meats = Meat.objects.get(pk=meat_id)

    except Meat.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'forms/meatedit.html', {'meats': meats})


def mproccessedit(request, meat_id):
    meats = get_object_or_404(Meat, pk=meat_id)
    profile_pic = request.FILES.get('image')
    try:
        mid = request.POST.get('pid')
        mname = request.POST.get('proname')
        mprice = request.POST.get('price')
        mcategory = request.POST.get('cat')
        msize = request.POST.get('size')

    except (KeyError, user.DoesNotExist):
        return render(request, 'admins_/mdetail.html', {
            'meats': meats,
            'error_message': "There is a problem on updating the record"
        })
    else:
        meat_profile = Meat.objects.get(id=meat_id)
        meat_profile.m_id = mid
        meat_profile.m_name = mname
        meat_profile.m_price = mprice
        meat_profile.m_cat = mcategory
        meat_profile.m_size = msize
        if profile_pic:
            meat_profile.m_image = profile_pic
        meat_profile.save()
        return HttpResponseRedirect(reverse('backend:mdetail', args=(meat_id, )))


#------------------------------------------------ product pancit--------------
    
def Productprocess(request):
    id= request.POST.get('pid')
    name = request.POST.get('proname')
    price = request.POST.get('price')
    category = request.POST.get('cat')
    size = request.POST.get('size')


    if request.FILES.get('image'):
        pro_pic = request.FILES.get('image')
    else:
        pro_pic = 'profile/image.jpg'
    try:
        n =Product.objects.get(pro_id=id)

        return render(request, 'forms/addpancit.html',{ 'error_message': "This product " + id +  "already exist"})

    except ObjectDoesNotExist:
        users = Product.objects.create(pro_id=id, pro_name=name, pro_price=price,  Catergoty=category, pro_size=size
                                    ,pro_image=pro_pic)
        users.save()

        return HttpResponseRedirect(reverse('backend:products'))



#------------------- Pancit Editing ---------



def pdetails(request, pancit_id):
    try:
        pancit = Product.objects.get(pk=pancit_id)

    except Product.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'admins_/pdetail.html', {'pancit': pancit})


# delete details
def pdelete(request,pancit_id):
    Product.objects.filter(id=pancit_id).delete()
    return HttpResponseRedirect(reverse('backend:products'))


# edits

def pedit(request, pancit_id):
    try:
        pancit = Product.objects.get(pk=pancit_id)

    except Productprocess.DoesNotExist:
        raise Http404("This user does not exist!!")

    return render(request, 'forms/pancitedit.html', {'pancit': pancit})


def pproccessedit(request, pancit_id):
    pancit = get_object_or_404(Product, pk=pancit_id)
    profile_pic = request.FILES.get('image')
    try:
        id = request.POST.get('pid')
        name = request.POST.get('proname')
        price = request.POST.get('price')
        category = request.POST.get('cat')
        size = request.POST.get('size')

    except (KeyError, Productprocess.DoesNotExist):
        return render(request, 'admins_/pdetail.html', {
            'pancit': pancit,
            'error_message': "There is a problem on updating the record"
        })
    else:
        pancit_profile = Product.objects.get(id=pancit_id)
        pancit_profile.m_id = id
        pancit_profile.m_name = name
        pancit_profile.m_price = price
        pancit_profile.Catergoty = category

backend/templates/admins_/Home.html
 {% extends 'partials/base2.html' %}



{% block title %}

 Login

 {% endblock %}


{% block content %}





   <style>
        body {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFE);
}

.btn-login {
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
}

.btn-google {
  color: white !important;
  background-color: #ea4335;
}

.btn-facebook {
  color: white !important;
  background-color: #3b5998;
}




       
   </style>


<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
          <div class="card-body p-4 p-sm-5">

            <h5 class="card-title text-center mb-5 fw-light fs-5">Luna X Sky Cafe </h5>
                {% if error_message %}
                         <p class="alert alert-danger">
                             <strong> {{ error_message }} </strong>
                         </p>
                        {% endif %}

         <form action="{% url 'backend:Loginprocess' %}" method="post">
                            {% csrf_token %}
              <div class="form-floating mb-3">
                <input  type="text" name="username" id="username" class="form-control" placeholder="enter username"
                                autocomplete="off">
                <label for="floatingInput">Email address</label>
              </div>
              <div class="form-floating mb-3">
               <input  type="password" name="password" id="password" class="form-control" placeholder="enter password"
                                >
                <label for="floatingPassword">Password</label>
              </div>

              <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" value="" id="rememberPasswordCheck">
                <label class="form-check-label" for="rememberPasswordCheck">
                  Remember password
                </label>
              </div>
              <div class="d-grid">
                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign
                  in</button>
              </div>
              
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/admins_/detail.html
{% extends 'base.html' %}

{% block title %}

    {{users.user_position}} - {{users.user_fname}} {{users.user_lname}}

{% endblock %}



{% block content %}


<style>

.content{
    position: center;
}

.containers{
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
  margin-left: 25%;
  margin-top: 10px;
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}


</style>



              <div class="containers text-center">
                  
                  <div class="ima=g-responsive text-center">
                      
                      
                      <img src="/backend/media/{{users.user_image}}"alt="profile_user" class="img-rounded" width="300">
                  </div>
               <div class="containers">
                     <h3> {{users.user_fname}} {{users.user_lname}}</h3>
                     <p class="text-muted">Username: {{ users.user_username}} </p>
                     <p >Position: {{ users.user_position}} </p>
                     <p > {{ users.pub_date}} </p>
                     <p > {{ users.user_uid}} </p>



                     <div class="btn-group" role="group" aria-label="Basic example">
                         <a href="{% url 'backend:deletes' users.id %}" class="btn btn-sm btn-danger"> DELETE</a>
                         <a href="{% url 'backend:edits' users.id %}"class="btn btn-sm btn-info"> EDIT </a>
                         <a href="{% url 'backend:accounts' %}" class="btn btn-sm btn-success"> RETURN </a>
</div>
 </div>                                                              
</div>



    

{% endblock %}

backend/templates/admins_/mdetail.html
{% extends 'base.html' %}

{% block title %}

    {{users.user_position}} - {{users.user_fname}} {{users.user_lname}}

{% endblock %}



{% block content %}


<style>

.content{
    position: center;
}

.containers{
  width: 50%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0,0,0,0.15);
  margin-left: 25%;
  margin-top: 10px;
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}
.containers .title::before{
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 3px;
  width: 30px;
  border-radius: 5px;
  background: linear-gradient(135deg, #71b7e6, #9b59b6);
}





</style>



              <div class="containers text-center">

                  <div class="ima=g-responsive text-center">


                      <img src="/backend/media/{{meats.m_image}}"alt="profile_user" class="img-rounded" width="300">
                  </div>
               <div class="containers">
                     <h3> {{ meats.m_id}} </h3>
                     <p class="text-muted">{{ meats.m_name}}</p>
                     <p >{{ meats.m_price}}</p>
                     <p >{{ meats.m_cat}} </p>
                     <p > {{ meats.m_price}} </p>



                     <div class="btn-group" role="group" aria-label="Basic example">
                         <a href="{% url 'backend:mdelete' meats.id %}" class="btn btn-sm btn-danger">DELETE</a>
                         <a href="{% url 'backend:medit' meats.id %}"class="btn btn-sm btn-info">EDIT</a>
                         <a href="{% url 'backend:products' %}" class="btn btn-sm btn-success">RETURN</a>
</div>
 </div>
</div>





{% endblock %}

backend/templates/admins_/products.html
{% extends 'base.html' %}

{% block title %}
    Products 
{% endblock %}

{% block content %}

<style>
 .containers{
  width: 100%;
  background-color: #fff;
  padding: 25px 30px;
  border-radius: 5px;
  border: black;
  box-shadow: 0 5px 10px rgba(15,12,12.15);
}
.containers .title{
  font-size: 25px;
  font-weight: 500;
  position: relative;
}




</style>


        <h1 class="mb-4"> Manage Product </h1>

        <div class="containers">
             <h1 class="mb-4"> MENU </h1>
                               <a href="products">
                   </a>

                                                                                                                                            
     <div class="container">

               <form action="{% url 'backend:psearch' %}" method="GET">
                        <div class="input-group mb-4">
                          <input type="search" class="form-control rounded"  name="psearch" placeholder="Search" aria-label="Search" aria-describedby="search-addon" required>
                          <div class="input-group-append">

                         <a href=""> <button type="submit" class="btn btn-outline-primary"><i class="fa fa-search"></i> search</button> </a>

                       </div>
                      </div>
                    </form>

              <a href="pancitpage">
              <button type="button" class="btn btn-primary btn-lg" style="float:right; margin-left: 20px; font-size:12px"><i class="fa fa-plus" aria-hidden="true"> ADD PRODUCT </i></button></a>
                                 <button type="submit" class="btn btn-outline-primary" style="float: right"><i class="fa fa-refresh"></i>
                           refresh
                       </button>

    <!-- data presents -->
    {% if pro_list %}

        <div class="table-responsive" style="height: 500px;overflow: scroll;">
           <table class="table table-bordered table-striped table-hover">
`
                    <thead>
                        <tr style="text-align: justify;">

                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Product id
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  image </th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Name</th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Prize</th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Size</th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  category</th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Action</th>
                            <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Delete </th>


                        </tr>
                    </thead>

                    <tbody>

                        {% for Product in pro_list %}
                        <tr>
                            <td> {{ Product.pro_id }}    </td>
                            <td class="text-center"><img src="media/{{Product.pro_image}}" alt="userimage0" width="50" class="rounded-cricle"></td>
                            <td>  {{ Product.pro_name }}    </td>
                            <td>  {{ Product.pro_price }}   </td>
                            <td>  {{ Product.pro_size}}   </td>
                            <td>  {{ Product.Catergoty}}   </td>

                            <td><a href="{% url 'backend:pdetails' Product.id %}" class="btn btn-sm btn-success"> View </a></td>
                            <td><a href="{% url 'backend:pdelete' Product.id %}" class="btn btn-sm btn-danger">DELETE</a></td>

                        </tr>

                          {% endfor %}
                    </tbody>
                </table>
        </div>
         {% else %}

         <p class="text-muted" style="text-align: center; font-size: 20pt"> No product available</p>

         {% endif %}

        </div>

    </div>


<!--- meat shops -->       <!--- meat shops -->          <!--- meat shops -->
   <!--- meat shops -->      <!--- meat shops -->                <!--- meat shops -->
<!--- meat shops -->            <!--- meat shops -->                <!--- meat shops -->


 <div class="containers mt-2">

    
             <h1 class="mb-4 mt-4"> OTHER PRODUCT </h1>


             <div class="container">
                  <form action="{% url 'backend:search' %}" method="GET">
                        <div class="input-group mb-4">
                          <input type="search" class="form-control rounded"  name="search" placeholder="Search" aria-label="Search" aria-describedby="search-addon" required>
                          <div class="input-group-append">
                          <button type="submit" class="btn btn-outline-primary"><i class="fa fa-search"></i> search</button>
                       </div>
                      </div>

                   </form>


               <a href="meatpage">
                <button type="button" class="btn btn-primary btn-lg" style="float:right; margin-left: 20px ; font-size:12px"><i class="fa fa-plus" aria-hidden="true"> ADD PRODUCT </i></button>
               </a>


                <!-- data presents -->
                {% if m_list %}

                    <div class="table-responsive" style="height: 500px;overflow: scroll;">
                    <table class="table table-bordered table-striped table-hover">

                        <thead>
                            <tr>

                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Product id  </th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  image </th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Name</th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Prize</th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Size</th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  category</th>
                                <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Action </th>
                                 <th scope="col" style="position: sticky;  top: 0; background: #727272;">  Delete </th>


                            </tr>
                        </thead>

                        <tbody>

                            {% for Meat in m_list %}
                            <tr>
                                <td> {{ Meat.m_id }}    </td>
                                <td class="text-center"><img src="media/{{Meat.m_image}}" alt="userimage0" width="50" class="rounded-cricle"></td>
                                <td>  {{ Meat.m_name }}    </td>
                                <td>  {{ Meat.m_price }}   </td>
                                <td>  {{ Meat.m_price }}   </td>
                                <td>  {{ Meat.m_cat}}   </td>
                                 <td><a href="{% url 'backend:mdetail' Meat.id %}" class="btn btn-sm btn-success"> View </a></td>
                                 <td><a href="{% url 'backend:mdelete' Meat.id %}" class="btn btn-sm btn-danger">DELETE</a></td>

                            </tr>
                              {% endfor %}
                        </tbody>
                    </table>
                    </div>
                 {% else %}

                         <p class="text-muted" style="text-align: center; font-size: 20pt"> No product available</p>


              {% endif %}
             </div>
</div>

{% endblock %}