Ordering_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('main/',include('main.urls')),




]

main/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
                  path('store', views.store, name="store"),
                  path('cart/', views.cart, name="cart"),
                  path('checkout/', views.checkout, name="checkout"),

                  path('update_item/', views.updateItem, name="update_item"),
                  path('process_order/', views.processOrder, name="process_order"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from backend.models import Product

# Create your models here.

class Customer(models.Model):
    user =   models.OneToOneField(User, on_delete=models.CASCADE,null=True, blank=True)
    name  =   models.CharField(max_length=200, null=True)
    email =   models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return  str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.products.digital == False:
                    shipping = True
        return shipping





class orderitem(models.Model):
    products = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    orders =  models.ForeignKey(order, on_delete=models.SET_NULL , null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added= models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.products.pro_price * self.quantity
        return total


class Shippingaddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(order,on_delete=models.SET_NULL, null=True, blank=True)
    items = models.ForeignKey(orderitem, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.CharField(max_length=200, null=False)
    state= models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


    
    

main/views.py
import datetime
import json    ,sys
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.shortcuts import render
from .models import *
from .utils import cookieCart, cartData , guestOrder


# Create your views here.


def store(request):
    data = cartData(request)
    cartItems = data['cartItems']
    

    products = Product.objects.all()
    context = {'products': products, 'cartItems': cartItems}
    return render(request, 'front/store.html', context)

@csrf_exempt
def cart(request):
    
    data = cartData(request)
    cartItems = data['cartItems']
    orders = data['orders']
    items = data['items']

    context ={
        'orders': orders,
        'items':items,
        'cartItems': cartItems}

    return render(request, 'front/cart.html', context)

@csrf_exempt
def checkout(request):

    data = cartData(request)
    cartItems = data['cartItems']
    orders = data['orders']
    items = data['items']

    context = {'items': items,'orders': orders, 'cartItems': cartItems }
    return render(request, 'front/checkout.html', context)


@csrf_exempt
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    orders, created = order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = orderitem.objects.get_or_create(orders=orders, products=product)
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)
@csrf_exempt
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        orders, created = order.objects.get_or_create(customer=customer, complete = False)
        
       
    else:
        customer, orders = guestOrder(request, data)
    
    total = float(data['form']['total'])
    orders.transation_id = transaction_id

    if total == float(orders.get_cart_total):
        orders.complete = True
    orders.save()

    if orders.shipping == True:
        Shippingaddress.objects.create(
            customer=customer,
            order=orders,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment Complete', safe=False)

main/templates/Front/cart.html
{% extends 'base2.html' %}
{% load static %}


{% block title %}

     {{ user }} | Cart

{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'main:store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{ orders.get_cart_items }}</strong></h5></th>
						<th><h5>Total:<strong>   ₱ {{ orders.get_cart_total }}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'main:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				     {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="/backend/media/{{item.products.pro_image}}"></div>
					<div style="flex:2"><p>{{ item.products.pro_name}}</p></div>
					<div style="flex:1"><p>          ₱ {{ item.products.pro_price}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{ item.quantity}}</p>
						<div class="quantity">
							<img data-product={{item.products.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

							<img data-product={{item.products.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>          ₱ {{ item.get_total }}</p></div>
				</div>
				            {% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

main/templates/Front/checkout.html
{% extends 'base2.html' %}
{% load static %}


{% block title %}

     {{ user }} | Checkout

{% endblock %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					    {% csrf_token %}
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						
						<hr>                                      	
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="Street">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="City">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Contact number">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Add message for some you wanted to greet">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				 <div id="paypal-button-container"></div>
				<!--button	id="make-payment">Make Payment</button-->
			</div>

		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'main:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
					<h5>Items:   {{  orders.get_cart_items }} </h5>
					<h5 style="padding-right: 50px">Total:          ₱ {{ orders.get_cart_total }}</h5>
				<hr>
				 {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="/backend/media/{{item.products.pro_image}}"></div>
					<div style="flex:2"><p>{{ item.products.pro_name}}</p>
										<p>	{{item.products.Catergoty}} </p>
										<p>	{{item.products.pro_size}}  </p>
					</div>
					
					<div style="flex:1"><p>         ₱ {{ item.products.pro_price}}</p></div>
					<div style="flex:1"><p> {{ item.quantity}}x</p></div>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
 <script src="https://www.paypal.com/sdk/js?client-id=AZ4Z8lkwPV72Mly1SXPznfltmjGhHVHJzs1vxxRazTPrkAaPA9IYQa4m1x2f8UJiw9yU2DRzcRCdHnou&currency=PHP&disable-funding=credit,card"></script>

<script>
        // Render the PayPal button into #paypal-button-container

  	var total = '{{orders.get_cart_total}}'

	paypal.Buttons({

		style:{
			color: 'blue',
			shape: 'rect',
		},

		createOrder: function(data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: parseFloat(total).toFixed(2)
					}
				}]
			});
		},


		onApprove: function(data, actions) {
			return actions.order.capture().then(function(orderData) {
				submitFormData()



			});
		}


	}).render('#paypal-button-container');

</script>

<script type ="text/javascript">

		var shipping  = '{{ orders.shipping }}'
	//	var total = '{{orders.get_cart_total}}'
		if(shipping == 'False'){
			document.getElementById('shipping-info').innerHTML = ''
	   	}

	   	if(user != 'AnonymousUser'){
	   		document.getElementById('user-info').innerHTML = ''
	   	}

	   	if(shipping == 'False' && user != 'AnonymousUser'){
	   		document.getElementById('form-wrapper').classList.add('hidden');

	   	    document.getElementById('payment-info').classList.remove('hidden');
	   	}
	   	

	   	var form = document.getElementById('form')
		csrftoken = form.getElementsByTagName('input')[0].value
		console.log('Newtoken:', form.getElementsByTagName('input')[0].value)
	   	form.addEventListener('submit', function(e){
	   		e.preventDefault()
			console.log('Form Submitted...')
	   		document.getElementById('form-button').classList.add('hidden')
	   		document.getElementById('payment-info').classList.remove('hidden')
	   		})
		/*
		document.getElementById('make-payment').addEventListener('click', function(e){
			submitFormData()  
		})
		*/ 

		function submitFormData(){
			console.log('Payment button clicked')

			var userFormData = {
				'name': null,
				'email': null,
				'total': total,
			}

			var shippingInfo = {
				'address': null,
				'city': null,
				'state': null,
				'zipcode': null,
			}

			if(shipping != 'False'){
				shippingInfo.address = form.address.value
				shippingInfo.city = form.city.value
				shippingInfo.state = form.state.value
				shippingInfo.zipcode = form.zipcode.value
			}

			if(user == 'AnonymousUser'){
				userFormData.name = form.name.value
				userFormData.email = form.email.value
			}

			var url = '/main/process_order/'
			fetch(url, {
				method: 'POST',
				headers:{
					'Content-Type' : 'application/json',
					'X-CSRFToken' : csrftoken,
				},
				body:JSON.stringify({'form' : userFormData, 'shipping' : shippingInfo})

			})
			.then((response) => response.json())
			.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');

				cart={}
				document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
				window.location.href = "{% url 'main:store' %}"

			})

		}

	  

</script>
{% endblock content %}

main/templates/Front/main.html
{% load static %}



<style>
    * {
    box-sizing: border-box;
  }

  body {
    margin: 0px;
    font-family: 'segoe ui';
  }

  .nav {
    height: 50px;
    width: 100%;
    background-color: grey;
    position: sticky;
  }

  .nav > .nav-header {
    display: inline;
  }

  .nav > .nav-header > .nav-title {
    display: inline-block;
    font-size: 22px;
    color: #fff;
    font-weight: 550;
    font-family: Arial, Helvetica, sans-serif;
    padding: 10px 10px 10px 10px;
  }

  .nav > .nav-btn {
    display: none;
  }

  .nav > .nav-links {
    display: inline;
    float: right;
    font-size: 18px;
  }
  .nav > .nav-links > ul li a{
    display: block;
    padding: 0 8px;
    color: #fff;
    line-height: 40px;
    font-size: 18px;
    text-decoration: none;

  }
  .nav > .nav-links > ul{
    padding: 0;
    margin-top: 5px;
    list-style: none;
    position: relative;

  }
  .nav > .nav-links > ul li{
    display: inline-block;
    background-color: none;


  }
  .nav > .nav-links > ul li:hover{
      background-color: #0b65af;
      border-radius: 5px;
  }

  .nav > #nav-check {
    display: none;
  }

 .nav .nav-links ul a.icon{
 margin-left: 80px;
 margin-right: 10px;
 }

 .nav .nav-links ul a i{
    background-color: #fff;
    border-radius: 50px;
    padding: 7px;
    margin-left: 5px;
 }


  @media (max-width:750px) {
    .nav > .nav-btn {
      display: inline-block;
      position: absolute;
      right: 0px;
      top: 0px;
    }
    .nav > .nav-btn > label {
      display: inline-block;
      width: 50px;
      height: 50px;
      padding: 13px;
    }
    .nav > .nav-btn > label:hover,.nav  #nav-check:checked ~ .nav-btn > label {
      background-color: rgba(0, 0, 0, 0.3);
    }
    .nav > .nav-btn > label > span {
      display: block;
      width: 25px;
      height: 10px;
      border-top: 2px solid #eee;
    }
    .nav > .nav-links {
      position: absolute;
      display: block;
      width: 100%;
      background-color: #333;
      height: 0px;
      transition: all 0.3s ease-in;
      overflow-y: hidden;
      top: 50px;
      left: 0px;
    }
    .nav > .nav-links > ul li a {
      display: block;
      width: 100%;
    }

    /*   */



      .nav > .nav-links > ul li{
        display: block;
        margin-bottom: 20px;
        padding: 0;
        background-color: #333;

      }
      .nav > .nav-links > ul li a{
          margin-left: 40%;
      }
      .nav .nav-links ul a.icon{
        margin-left: 33%;
      }

    /*   */
    .nav > #nav-check:not(:checked) ~ .nav-links {
      height: 0px;
    }
    .nav > #nav-check:checked ~ .nav-links {
      height: calc(100vh - 50px);
      overflow-y: auto;
    }
  }

  i {
   color: blue;
  }

</style>



<!--<div class="m-4 sticky-top ">-->
<!--    <nav class="navbar center sticky-top navbar-expand-lg navbar-light bg-light">-->
<!--        <div class="container-fluid">-->
<!--            <a href="{% url 'main:store' %}" class="navbar-brand">Luna x Sky Cafe</a>-->
<!--            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">-->
<!--                <span class="navbar-toggler-icon"></span>-->
<!--            </button>-->
<!--            <div class="collapse navbar-collapse" id="navbarCollapse">-->
<!--                <div class="navbar-nav">-->
<!--                    <a class="nav-item nav-link active" href="{% url 'main:store' %}"><i class="fa fa-dashboard" aria-hidden="true"></i> Menus </a>-->
<!--                    <a class="nav-item nav-link"href="{% url 'main:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i> CART {{ cartItems }} </a>-->
<!--                    <a class="nav-item nav-link" href="{% url 'main:checkout' %}"><i class="fa fa-paypal" aria-hidden="true"></i> CHECKOUT </a>-->
<!--                    {%  if user.is_authenticated %}-->
<!--                    <a class="nav-item nav-link" style="text-align: left;" href="{% url 'main:checkout' %}"><i class="fa fa-cart" aria-hidden="true"></i> Logout | login</a>-->
<!--                     {% endif %}-->
<!--                </div>-->
<!--                <div class="navbar-nav ms-auto">-->

<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </nav>-->
<!--</div>-->

<div class="nav sticky-top">
        <input type="checkbox" id="nav-check">
        <div class="nav-header">
          <div class="nav-title">
            <a style="color:white; text-decoration:none;" href="{% url 'main:store' %}">Luna x Sky Cafe</a>
          </div>
        </div>
        <div class="nav-btn">
          <label for="nav-check">
            <span></span>
            <span></span>
            <span></span>
          </label>
        </div>

        <div class="nav-links">
            <ul>
          <li> <a href="{% url 'main:store' %}"><i class="fa fa-dashboard" aria-hidden="true" ></i> Menus </a></li>
          <li><a class=""href="{% url 'main:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i> CART {{ cartItems }} </a></li>
          <li> <a class="" href="{% url 'main:checkout' %}"><i class="fa fa-paypal" aria-hidden="true"></i> CHECKOUT </a></li>
                <li><a href="#" target="_blank"><i class="fa fa-phone" aria-hidden="true"></i>Contact</a> </li>
          <li> {%  if user.is_authenticated %}
                    <a class="nav-item nav-link" style="text-align: left;" href="{% url 'main:checkout' %}"><i class="fa fa-cart" aria-hidden="true"></i> Logout | login</a>
           {% endif %}</li>
          <a class="icon" style="align:right;">
            <i class="fa fa-instagram"></i>
            <i class="fa fa-facebook"></i>

          </a>
            </ul>
        </div>
      </div>

main/templates/Front/store.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}

     {{ user }} | Store

{% endblock %}


{% block content %}

	<div class="row">
		<div> <h1 style="text-align: center"> LUNA X SKY CAFE </h1>
				<h4 style="text-align: center"> Available menus is here feel free to order</h4>
		</div>
		{% for Product in products %}
		<div class="col-lg-4 mt-0">

			<img src="media/{{Product.pro_image}}" alt="userimage0" HEIGHT="50%" width="100%" class="rounded-cricle">
			<div class="box-element product">
				<h3><strong> {{ Product.pro_name }}   </strong></h3>
				<h5><strong> Category :   {{ Product.Catergoty  }}   </strong></h5>
				<p style="font-size: 24px"> Size:    {{ Product.pro_size  }} </p>
				<hr>
				<button data-product = {{Product.id}} data-action= "add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<h4 style="display: inline-block; float: right"><strong>₱ {{ Product.pro_price }} </strong></h4>

			</div>
		</div>

		          {% endfor %}
	</div>

{% endblock content %}